version: '3.8'
services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    depends_on:
      - llm-service
      - elasticsearch
      - db
    environment:
      - FLASK_ENV=development

  llm-service:
    build: ./llm-service
    ports:
      - "8000:8000"
    volumes:
      - ./llm-service:/app

  elasticsearch:
    image: elasticsearch:8.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=datadungeons
      - POSTGRES_USER=dm
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  es-data:
  db-data: